Only mount volumes when running a job
This commit updates backup worker behavior to mount volumes at job
creation time. Without this change when a mount is created it is set to
ensure => mounted. The implication of this behavior is that when a
device backend is changed manual intervention is required to unmount the
currently used volume. This change supports placing the system into
maintenance mode, changing the backend storage configuration, and
letting the new volumes get mounted by the job as needed. The other
benefit of this change is it reduces load on the NFS server by
significantly reducing the number of simultaneous connections.

diff --git a/templates/run_backup.erb b/templates/run_backup.erb
--- a/templates/run_backup.erb
+++ b/templates/run_backup.erb
@@ -4,10 +4,8 @@ set -e
 cmd=$1
 mount_path='<%= @backup_dir %>'
 cmd_path='<%= @permitted_commands %>'
-check_mount=$(stat -f -L -c %T ${mount_path}/${cmd} | sed 's/\///')
 cmd_="${cmd_path}/${cmd}"
 export zpr_rsync_cmd=$(cat $cmd_)
-create_lock=$(lockfile-create -r 0 ${mount_path}/${cmd}/zpr_rsync &> /dev/null ; echo $?)
 maintenance_mode='<%= @home %>/.maintenance_mode'
 
 cmd_empty() {
@@ -26,7 +24,24 @@ check_maintenance_mode() {
   fi
 }
 
+mount_volume() {
+  check_mount=$(sudo /bin/mount ${mount_path}/${cmd} > /dev/null 2>&1 ; echo $?)
+  if [[ $check_mount -eq 32 ]]
+  then
+    >&2 echo "Requested volume is already mounted"
+  elif [[ $check_mount -ne 0 ]]
+  then
+    >&2 echo "Cannot mount volume"
+    exit 3
+  fi
+}
+
+unmount_volume() {
+  >&2 sudo /bin/umount ${mount_path}/${cmd}
+}
+
 path_is_nfs() {
+  check_mount=$(stat -f -L -c %T ${mount_path}/${cmd} | sed 's/\///')
   if [[ $check_mount != 'nfs' ]]
   then
     >&2 echo "Requested volume is not mounted"
@@ -35,6 +50,7 @@ path_is_nfs() {
 }
 
 check_lockfile() {
+  create_lock=$(lockfile-create -r 0 ${mount_path}/${cmd}/zpr_rsync &> /dev/null ; echo $?)
   if [[ $create_lock -ne 0 ]]
   then
     >&2 echo "A lock for $cmd exists"
@@ -61,13 +77,15 @@ check_if_exit_3() {
 main() {
   cmd_empty
   check_maintenance_mode
+  mount_volume
   path_is_nfs
   check_lockfile
   run_cmd
   remove_lock
+  unmount_volume
 }
 
-trap "remove_lock ; exit 255" SIGINT SIGQUIT SIGTERM
+trap "remove_lock && unmount_volume ; exit 255" SIGINT SIGQUIT SIGTERM
 trap "check_if_exit_3" EXIT
 
 main
diff --git a/templates/run_duplicity.erb b/templates/run_duplicity.erb
--- a/templates/run_duplicity.erb
+++ b/templates/run_duplicity.erb
@@ -11,7 +11,6 @@ target=$2
 full_every=$3
 remove_older_than=$4
 maintenance_mode=${HOME}/.maintenance_mode
-check_mount=$(stat -f -L -c %T ${source_files})
 
 duplicity_backup() {
   /usr/bin/duplicity --encrypt-key ${key_id} --sign-key ${sign_key} --full-if-older-than ${full_every} ${source_files} ${target}
@@ -30,18 +29,48 @@ check_maintenance_mode() {
 }
 
 path_is_nfs() {
-  if [[ $check_mount != 'nfs' ]]
+  check_nfs_mount=$(stat -f -L -c %T ${source_files})
+  if [[ $check_nfs_mount != 'nfs' ]]
   then
     >&2 echo "Requested volume is not mounted"
     exit 2
   fi
 }
 
+mount_volume() {
+  check_mount=$(sudo /bin/mount ${source_files} > /dev/null 2>&1 ; echo $?)
+  if [[ $check_mount -eq 32 ]]
+  then
+    >&2 echo "Requested volume is already mounted"
+  elif [[ $check_mount -ne 0 ]]
+  then
+    >&2 echo "Cannot mount volume"
+    exit 3
+  fi
+}
+
+unmount_volume() {
+  >&2 sudo /bin/umount ${source_files} > /dev/null 2>&1
+}
+
+check_tsp() {
+  check_tsp=$(tsp | grep 'running' | grep ${source_files} > /dev/null 2>&1 ; echo $?)
+  if [[ $check_tsp -eq 0 ]]
+  then
+  exit 1
+  fi
+}
+
 main() {
   check_maintenance_mode
+  check_tsp
+  mount_volume
   path_is_nfs
   duplicity_backup
   duplicity_cleanup
+  unmount_volume
 }
+
+trap "unmount_volume ; exit 255" SIGINT SIGQUIT SIGTERM EXIT
 
 main
